name: 'Test_Project'
version: '1.0.0'
profile: 'Test_Project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  Test_Project:
    business:
      +materialized: table